/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* biome-ignore-all lint: auto-generated */

/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_ASK_CLARA_API_URL: string
  readonly VITE_EVENT_BOOKING_API_URL: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}